openapi: "3.0.0"
info:
  title: "User API"
  version: "1.0.0"
paths:
  /user:
    post:
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        type: "aws_proxy"
        uri: "arn:aws:apigateway:eu-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-2:900332192728:function:user_lambda/invocations"
    get:
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        type: "aws_proxy"
        uri: "arn:aws:apigateway:eu-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-2:900332192728:function:user_lambda/invocations"
    patch:
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        type: "aws_proxy"
        uri: "arn:aws:apigateway:eu-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-2:900332192728:function:user_lambda/invocations"
    delete:
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        type: "aws_proxy"
        uri: "arn:aws:apigateway:eu-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-2:900332192728:function:user_lambda/invocations"
